/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    CivicPulse: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "id",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "reporter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "metadataHash",
              type: "string",
            },
          ],
          name: "ReportAnchored",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "id",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isResolved",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "string",
              name: "resolutionHash",
              type: "string",
            },
          ],
          name: "StatusUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_id",
              type: "string",
            },
            {
              internalType: "string",
              name: "_hash",
              type: "string",
            },
          ],
          name: "anchorReport",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllReportsLength",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_id",
              type: "string",
            },
            {
              internalType: "string",
              name: "_resolutionHash",
              type: "string",
            },
          ],
          name: "markResolved",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "reportIds",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "reports",
          outputs: [
            {
              internalType: "string",
              name: "internalId",
              type: "string",
            },
            {
              internalType: "address",
              name: "reporter",
              type: "address",
            },
            {
              internalType: "string",
              name: "metadataHash",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isResolved",
              type: "bool",
            },
            {
              internalType: "string",
              name: "resolutionHash",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
